services:
  db:
    image: mysql:latest
    container_name: mft-sql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
    volumes:
      - dbdata:/var/lib/mysql

  api:
    build: .
    container_name: mft-api
    ports:
      - "5000:5000"
    environment:
      - SQLUSER=root
      - PASSWORD=DS00jcezgoTJmhlkHlCX
      - HOSTNAME=containers-us-west-190.railway.app
      - DBPORT=7353
      - DBNAME=railway
volumes:
  dbdata: