services:
  db:
    image: mysql:latest
    container_name: mft-sql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=mft
    volumes:
      - dbdata:/var/lib/mysql

  api:
    build: .
    container_name: mft-api
    network_mode: "host"
    ports:
      - "8080:8080"
    environment:
      - SQLUSER=root
      - PASSWORD=pwd
      - HOSTNAME=127.0.0.1
      - DBPORT=3306
      - DBNAME=mft
volumes:
  dbdata: