services:
  db:
    image: mysql:latest
    container_name: mft-sql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: